site_name: ScaleIO-Framework
site_url: https://github.com/codedellemc/scaleio-framework
repo_url: https://github.com/codedellemc/scaleio-framework.git
docs_dir: .docs
site_dir: .site
theme_dir: .docs/.themes/yeti
#site_favicon: favicon.png

pages:
- Home: index.md
- User Guide:
    - Installation: user-guide/installation.md
    - Configuration: user-guide/configuration.md
    - Deployment Strategies: user-guide/deployment-strategies.md
    - Demo: user-guide/demo.md
    - Troubleshooting: user-guide/troubleshooting.md
    - Experimental: user-guide/experimental.md
- Developer guide:
    - Project guidelines: developer-guide/project-guidelines.md
    - REST API: developer-guide/restapi.md
    - Build reference: developer-guide/build-reference.md
    - Release process: developer-guide/release-process.md
- About:
    - Contributing: about/contributing.md
    - License: about/license.md
    - Release notes: about/release-notes.md
